# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_time', models.DateTimeField(auto_now_add=True, verbose_name='Pievienots')),
                ('product_updated', models.DateTimeField(auto_now=True, verbose_name='pēdējo reizi labots')),
                ('product_title', models.CharField(max_length=120, verbose_name='Produkta nosaukums')),
                ('product_content', models.TextField(verbose_name='Apraksts')),
                ('pruduct_slug', models.SlugField(unique=True)),
                ('product_rules1', models.CharField(blank=True, max_length=250, verbose_name='1. Uzstādīšanas nosacījums')),
                ('product_rules2', models.CharField(blank=True, max_length=250, verbose_name='2. Uzstādīšanas nosacījums')),
                ('product_rules3', models.CharField(blank=True, max_length=250, verbose_name='3. Uzstādīšanas nosacījums')),
                ('product_rules4', models.CharField(blank=True, max_length=250, verbose_name='4. Uzstādīšanas nosacījums')),
                ('product_rules5', models.CharField(blank=True, max_length=250, verbose_name='5. Uzstādīšanas nosacījums')),
                ('product_data', models.FileField(blank=True, upload_to='pdf', verbose_name='Detalizēta informācija (PDF)')),
                ('product_images', models.ImageField(blank=True, upload_to='img', verbose_name='Attēls 1')),
                ('product_images2', models.ImageField(blank=True, upload_to='img', verbose_name='Attēls 2')),
                ('product_images3', models.ImageField(blank=True, upload_to='img', verbose_name='Attēls 3')),
                ('product_images4', models.ImageField(blank=True, upload_to='img', verbose_name='Attēls 4')),
                ('product_category', models.CharField(choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 1')),
                ('product_category2', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 2')),
                ('product_category3', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 3')),
                ('product_category4', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 4')),
                ('product_category5', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 5')),
                ('product_category6', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 6')),
                ('product_category7', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 7')),
                ('product_category8', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 8')),
                ('product_category9', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 9')),
                ('product_category10', models.CharField(blank=True, choices=[('Sienas', 'Sienas'), ('Fasādes', 'Fasādes'), ('Grīdas', 'Grīdas'), ('Jumti', 'Jumti'), ('Ugunsdrošība', 'Ugunsdrošība'), ('Balkoni', 'Balkoni'), ('Pamati un cokols', 'Pamati un cokols'), ('Hobijs', 'Hobijs'), ('Ceļu konstrukcijas', 'Ceļu konstrukcijas'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju 10')),
            ],
            options={
                'verbose_name_plural': 'Mūsu produkti',
                'db_table': 'Mūsu produkti',
                'verbose_name': 'Mūsu produkti',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references_time', models.DateTimeField(auto_now_add=True, verbose_name='Pievienots')),
                ('references_updated', models.DateTimeField(auto_now=True, verbose_name='pēdējo reizi labots')),
                ('references_image', models.ImageField(upload_to='img', verbose_name='Izvēlēties attēlu')),
                ('image_category', models.CharField(choices=[('Privātmājas', 'Privātmājas'), ('Dzīvojamās mājas', 'Dzīvojamās mājas'), ('Komercbūves', 'Komercbūves'), ('Industriālās būves', 'Industriālās būves'), ('Pamati un cokols', 'Pamati un cokols'), ('Balkoni', 'Balkoni'), ('Pamatnes', 'Pamatnes'), ('Individuālie risinājumi', 'Individuālie risinājumi')], max_length=30, verbose_name='Izvēlēties kategoriju')),
            ],
            options={
                'verbose_name_plural': 'Galerija',
                'db_table': 'References',
                'verbose_name': 'Galerija',
            },
        ),
    ]
