# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160607_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pruduct_slug',
        ),
    ]
