# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_pruduct_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_time', models.DateTimeField(auto_now_add=True, verbose_name='Pievienots')),
                ('instruction_updated', models.DateTimeField(auto_now=True, verbose_name='pēdējo reizi labots')),
                ('instruction_name', models.CharField(max_length=150, verbose_name='Instrukcijas nosaukums')),
                ('instruction_category', models.CharField(choices=[('cat1', 'Garantijas noteikumi'), ('cat2', 'Plākšņu montāžas instrukcijas un pielietojumi'), ('cat3', 'Plākšņu sertifikāti un ekspluatācijas īpašību deklerācijas')], max_length=150, verbose_name='Izvēlēties kategoriju')),
                ('instruction_data', models.FileField(blank=True, upload_to='pdf', verbose_name='Instrukcija (PDF)')),
            ],
            options={
                'verbose_name': 'Instrukcijas',
                'db_table': 'Instructions',
            },
        ),
    ]
